source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-archives"
gem "jekyll_picture_tag", "~> 2.0"
gem "webrick"
gem "faraday-retry"
gem "kramdown-parser-gfm"
gem "sass-embedded", "~> 1.69.0"